FROM docker.io/golang:1.21

ARG BIN_PATH

WORKDIR $GOPATH/src/gophermart

COPY . .

# Fetch dependencies.
RUN go mod download
RUN go mod verify

COPY ./cmd/accrual/accrual_linux_amd64 $BIN_PATH/

# Build the binary
RUN GOOS=linux GOARCH=amd64 go build -buildvcs=false -o $BIN_PATH/gophermart ./cmd/gophermart

# Get latest praktikum test tools
RUN wget -O $BIN_PATH/gophermarttest https://github.com/Yandex-Practicum/go-autotests/releases/download/v0.10.1/gophermarttest
RUN wget -O $BIN_PATH/random https://github.com/Yandex-Practicum/go-autotests/releases/download/v0.10.1/random
RUN wget -O $BIN_PATH/statictest https://github.com/Yandex-Practicum/go-autotests/releases/download/v0.10.1/statictest
RUN chmod -R +x $BIN_PATH

RUN go vet -vettool=$BIN_PATH/statictest ./...

CMD gophermarttest \
      -test.v -test.run=^TestGophermart$ \
      -gophermart-binary-path=gophermart \
      -gophermart-host=localhost \
      -gophermart-port=8080 \
      -gophermart-database-uri="postgresql://postgres:postgres@postgres/praktikum?sslmode=disable" \
      -accrual-binary-path=accrual_linux_amd64 \
      -accrual-host=localhost \
      -accrual-port=$(random unused-port) \
      -accrual-database-uri="postgresql://postgres:postgres@postgres/praktikum?sslmode=disable"