version: '3.8'

services:
  db:
    container_name: ${APP_NAME}-test-db-dev
    image: postgres:14.4-alpine
    hostname: ${DB_PG_ENDPOINT}
    environment:
      - POSTGRES_PASSWORD=${DB_PG_PASSWORD}
      - POSTGRES_USER=${DB_PG_USER}
    # volumes:
    #   - pg:/var/lib/postgresql/data
    ports:
      - ${HOST}:${DB_PG_PORT}:${DB_PG_PORT}
    restart: unless-stopped
    networks:
      - db
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  tests:
    container_name:  ${APP_NAME}-tests
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db
    networks:
      - db

networks:
  db:

volumes:
  pg:
    name: ${APP_NAME}-test-pg